export enum BusinessSector {
    RESTAURANT = "RESTAURANT",
    VETERINARY = "VETERINARY",
    RETAIL = "RETAIL",
    TECHNOLOGY = "TECHNOLOGY",
    HEALTHCARE = "HEALTHCARE",
    FINANCE = "FINANCE",
    EDUCATION = "EDUCATION",
    TRANSPORTATION = "TRANSPORTATION",
    CONSTRUCTION = "CONSTRUCTION",
    ENTERTAINMENT = "ENTERTAINMENT",
    MANUFACTURING = "MANUFACTURING",
    AGRICULTURE = "AGRICULTURE",
    REAL_ESTATE = "REAL_ESTATE",
    HOSPITALITY = "HOSPITALITY",
    CONSULTING = "CONSULTING"
}
