export enum ServiceTag {
    LIMPIEZA = "LIMPIEZA",
    FONTANERIA = "FONTANERIA",
    ELECTRICIDAD = "ELECTRICIDAD",
    JARDINERIA = "JARDINERIA",
    ENTREGA = "ENTREGA",
    TRANSPORTE = "TRANSPORTE",
    SOPORTE_TECNICO = "SOPORTE_TECNICO",
    MANTENIMIENTO = "MANTENIMIENTO",
    TUTORIA = "TUTORIA",
    CATERING = "CATERING",
    REPARACION_HOGAR = "REPARACION_HOGAR",
    FOTOGRAFIA = "FOTOGRAFIA",
    ORGANIZACION_EVENTOS = "ORGANIZACION_EVENTOS",
    ENTRENAMIENTO_FISICO = "ENTRENAMIENTO_FISICO",
    BELLEZA_Y_BIENESTAR = "BELLEZA_Y_BIENESTAR"
}
